import { z } from 'npm:zod';

const envSchema = z.object({
  SUPABASE_DB_URL: z.string().optional(),
  DATABASE_URL: z.string().optional(),
  PGSSLMODE: z.enum(['disable', 'prefer', 'require']).default('disable'),
  JWT_SECRET: z.string().min(8).default('dev-secret-change-me'),
  JWT_EXPIRES_IN: z.string().default('7d'),
  ADMIN_EMAIL: z.string().email().default('owner@example.com'),
  ADMIN_PASSWORD: z.string().min(8).default('ChangeMe123!'),
  CAPTCHA_PROVIDER: z.string().trim().default(''),
  CAPTCHA_SECRET: z.string().trim().default(''),
  APPLE_PASS_TYPE_ID: z.string().trim().default(''),
  APPLE_TEAM_ID: z.string().trim().default(''),
  APPLE_CERT_PATH: z.string().trim().default(''),
  APPLE_CERT_PASSWORD: z.string().trim().default(''),
  APPLE_WWDR_CERT_PATH: z.string().trim().default(''),
  APNS_KEY_PATH: z.string().trim().default(''),
  APNS_KEY_ID: z.string().trim().default(''),
  GOOGLE_WALLET_ISSUER_ID: z.string().trim().default(''),
  GOOGLE_WALLET_SERVICE_ACCOUNT_JSON: z.string().trim().default(''),
  POS_TOKEN_ENC_KEY: z.string().trim().default(''),
  POS_STATE_SECRET: z.string().trim().default('dev-pos-state-secret'),
  VENDOR_PORTAL_URL: z.string().url().default('http://localhost:5174'),
  SQUARE_APP_ID: z.string().trim().default(''),
  SQUARE_APP_SECRET: z.string().trim().default(''),
  SQUARE_ENV: z.enum(['sandbox', 'production']).default('sandbox'),
  SQUARE_REDIRECT_URL: z.string().url().default('http://localhost:54321/functions/v1/router/api/pos/oauth/callback'),
  CLOVER_CLIENT_ID: z.string().trim().default(''),
  CLOVER_CLIENT_SECRET: z.string().trim().default(''),
  CLOVER_REDIRECT_URL: z.string().url().default('http://localhost:54321/functions/v1/router/api/pos/oauth/callback'),
  TOAST_CLIENT_ID: z.string().trim().default(''),
  TOAST_CLIENT_SECRET: z.string().trim().default(''),
  TOAST_REDIRECT_URL: z.string().url().default('http://localhost:54321/functions/v1/router/api/pos/oauth/callback'),
  STRIPE_CLIENT_ID: z.string().trim().default(''),
  STRIPE_CLIENT_SECRET: z.string().trim().default(''),
  STRIPE_REDIRECT_URL: z.string().url().default('http://localhost:54321/functions/v1/router/api/pos/oauth/callback'),
  APP_STORE_URL: z.string().url().default('https://apps.apple.com/'),
  PLAY_STORE_URL: z.string().url().default('https://play.google.com/store'),
  ALLOWED_ORIGINS: z.string().trim().default(''),
  BLOCKED_IPS: z.string().trim().default(''),
  MAILJET_API_KEY: z.string().trim().default(''),
  MAILJET_SECRET_API_KEY: z.string().trim().default(''),
  MAILJET_FROM_EMAIL: z.string().email().default('noreply@lightraildeals.com'),
  MAILJET_FROM_NAME: z.string().trim().default('Light Rail Deals'),
  MAILJET_SMS_TOKEN: z.string().trim().default(''),
  REDEEM_BASE_URL: z.string().trim().default(''),
  PASSCREATOR_API_KEY: z.string().trim().default(''),
  PASSCREATOR_BASE_URL: z.string().url().default('https://app.passcreator.com/api/v3'),
  PASSCREATOR_TEMPLATE_ID: z.string().trim().default(''),
  PASSCREATOR_TEMPLATEID: z.string().trim().default(''),
  SUPABASE_URL: z.string().trim().default(''),
  SUPABASE_SERVICE_ROLE_KEY: z.string().trim().default(''),
  SUPABASE_STORAGE_BUCKET: z.string().trim().default('lr-assets'),
  PUBLIC_API_BASE_URL: z.string().trim().default(''),
  EXPO_ACCESS_TOKEN: z.string().trim().default(''),
  BRAND_NAME: z.string().trim().default('Light Rail Deals'),
  WALLET_BACKGROUND_COLOR: z.string().trim().default('#0B1F3A'),
  WALLET_FOREGROUND_COLOR: z.string().trim().default('#FFFFFF'),
  WALLET_LABEL_COLOR: z.string().trim().default('#8FB2D9'),
});

const parsed = envSchema.parse(Deno.env.toObject());

export const config = {
  databaseUrl: parsed.SUPABASE_DB_URL ?? parsed.DATABASE_URL ?? '',
  pgSslMode: parsed.PGSSLMODE,
  jwtSecret: parsed.JWT_SECRET,
  jwtExpiresIn: parsed.JWT_EXPIRES_IN,
  adminEmail: parsed.ADMIN_EMAIL,
  adminPassword: parsed.ADMIN_PASSWORD,
  captchaProvider: parsed.CAPTCHA_PROVIDER,
  captchaSecret: parsed.CAPTCHA_SECRET,
  applePassTypeId: parsed.APPLE_PASS_TYPE_ID,
  appleTeamId: parsed.APPLE_TEAM_ID,
  appleCertPath: parsed.APPLE_CERT_PATH,
  appleCertPassword: parsed.APPLE_CERT_PASSWORD,
  appleWwdrCertPath: parsed.APPLE_WWDR_CERT_PATH,
  apnsKeyPath: parsed.APNS_KEY_PATH,
  apnsKeyId: parsed.APNS_KEY_ID,
  googleWalletIssuerId: parsed.GOOGLE_WALLET_ISSUER_ID,
  googleWalletServiceAccountJson: parsed.GOOGLE_WALLET_SERVICE_ACCOUNT_JSON,
  posTokenEncKey: parsed.POS_TOKEN_ENC_KEY,
  posStateSecret: parsed.POS_STATE_SECRET,
  vendorPortalUrl: parsed.VENDOR_PORTAL_URL,
  squareAppId: parsed.SQUARE_APP_ID,
  squareAppSecret: parsed.SQUARE_APP_SECRET,
  squareEnv: parsed.SQUARE_ENV,
  squareRedirectUrl: parsed.SQUARE_REDIRECT_URL,
  cloverClientId: parsed.CLOVER_CLIENT_ID,
  cloverClientSecret: parsed.CLOVER_CLIENT_SECRET,
  cloverRedirectUrl: parsed.CLOVER_REDIRECT_URL,
  toastClientId: parsed.TOAST_CLIENT_ID,
  toastClientSecret: parsed.TOAST_CLIENT_SECRET,
  toastRedirectUrl: parsed.TOAST_REDIRECT_URL,
  stripeClientId: parsed.STRIPE_CLIENT_ID,
  stripeClientSecret: parsed.STRIPE_CLIENT_SECRET,
  stripeRedirectUrl: parsed.STRIPE_REDIRECT_URL,
  appStoreUrl: parsed.APP_STORE_URL,
  playStoreUrl: parsed.PLAY_STORE_URL,
  allowedOrigins: parsed.ALLOWED_ORIGINS.split(',').map((item) => item.trim()).filter(Boolean),
  blockedIps: parsed.BLOCKED_IPS.split(',').map((item) => item.trim()).filter(Boolean),
  mailjetApiKey: parsed.MAILJET_API_KEY,
  mailjetSecretApiKey: parsed.MAILJET_SECRET_API_KEY,
  mailjetFromEmail: parsed.MAILJET_FROM_EMAIL,
  mailjetFromName: parsed.MAILJET_FROM_NAME,
  mailjetSmsToken: parsed.MAILJET_SMS_TOKEN,
  redeemBaseUrl: parsed.REDEEM_BASE_URL.replace(/\/$/, ''),
  passcreatorApiKey: parsed.PASSCREATOR_API_KEY,
  passcreatorBaseUrl: parsed.PASSCREATOR_BASE_URL.replace(/\/$/, ''),
  passcreatorTemplateId: parsed.PASSCREATOR_TEMPLATE_ID || parsed.PASSCREATOR_TEMPLATEID,
  supabaseUrl: parsed.SUPABASE_URL.replace(/\/$/, ''),
  supabaseServiceRoleKey: parsed.SUPABASE_SERVICE_ROLE_KEY,
  storageBucket: parsed.SUPABASE_STORAGE_BUCKET,
  publicApiBaseUrl: parsed.PUBLIC_API_BASE_URL.replace(/\/$/, ''),
  expoAccessToken: parsed.EXPO_ACCESS_TOKEN,
  brandName: parsed.BRAND_NAME,
  walletBackgroundColor: parsed.WALLET_BACKGROUND_COLOR,
  walletForegroundColor: parsed.WALLET_FOREGROUND_COLOR,
  walletLabelColor: parsed.WALLET_LABEL_COLOR,
} as const;

export type AppConfig = typeof config;
