-- Seed the Valley Metro rail stops from the original mobile hardcoded list.
-- Safe to rerun: duplicate names are ignored.

INSERT INTO stops (name, city, line, position)
SELECT t.name, t.city, t.line, t.position
FROM unnest(
  ARRAY['Downtown Phx Hub / Jefferson St', 'Downtown Phx Hub / Washington St', '3rd St / Jefferson', '3rd St / Washington', '12th St / Jefferson', '12th St / Washington', '24th St / Jefferson', '24th St / Washington', '38th St / Washington', '44th St / Washington', '50th St / Washington St', 'Priest Dr / Washington St', 'Center Pkwy / Washington', 'Veterans Way / College Ave', 'Mill Ave / 3rd St', 'University Dr / Rural Rd', 'Dorsey Ln / Apache Blvd', 'McClintock Dr / Apache Blvd', 'Smith-Martin / Apache Blvd', 'Price-101 Fwy / Apache Blvd', 'Sycamore / Main St', 'Alma School / Main St', 'Country Club / Main St', 'Center / Main St', 'Mesa Dr / Main St', 'Stapley Dr / Main St', 'Gilbert Rd / Main St', 'Baseline / Central Ave', 'Southern / Central Ave', 'Roeser / Central Ave', 'Broadway / Central Ave', 'Buckeye / Central Ave', 'Lincoln / Central Ave', 'Lincoln / 1st Ave', 'Jefferson / 1st Ave', 'Washington / Central Ave', 'Downtown Phx Hub / Central Ave', 'Downtown Phx Hub / 1st Ave', 'Van Buren / Central Ave', 'Van Buren / 1st Ave', 'Roosevelt / Central Ave', 'McDowell / Central Ave', 'Encanto / Central Ave', 'Thomas / Central Ave', 'Osborn / Central Ave', 'Indian School / Central Ave', 'Campbell / Central Ave', 'Central Ave / Camelback', '7th Ave / Camelback', '19th Ave / Camelback', 'Montebello / 19th Ave', 'Glendale / 19th Ave', 'Northern / 19th Ave', '19th Ave / Dunlap', 'Dunlap / 25th Ave', 'Mountain View / 25th Ave', 'Metro Parkway'],
  ARRAY['Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Tempe', 'Tempe', 'Tempe', 'Tempe', 'Tempe', 'Tempe', 'Tempe', 'Tempe', 'Tempe', 'Mesa', 'Mesa', 'Mesa', 'Mesa', 'Mesa', 'Mesa', 'Mesa', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix', 'Phoenix'],
  ARRAY['A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'A Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line', 'B Line'],
  ARRAY[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56]
) AS t(name, city, line, position)
ON CONFLICT (name) DO NOTHING;
