// Arizona Master Events Calendar (September 2026 – August 2027).
// Statewide events beyond the light-rail cities, shown on the
// "Events Around Arizona" screen. Static curated content — no API.

export type AzAdmission = 'free' | 'paid' | 'mixed' | 'tbd';

export interface AzEvent {
  date: string;
  name: string;
  location: string;
  category: string;
  admission: AzAdmission;
}

export interface AzMonth {
  month: string;
  events: AzEvent[];
}

type Row = [date: string, name: string, location: string, category: string, admission: AzAdmission];

function month(title: string, rows: Row[]): AzMonth {
  return { month: title, events: rows.map(([date, name, location, category, admission]) => ({ date, name, location, category, admission })) };
}

export const AZ_EVENT_MONTHS: AzMonth[] = [
  month('September 2026', [
    ['Sept. 17–Oct. 4', 'FlagShakes', 'Flagstaff / Various', 'Theater', 'paid'],
    ['Sept. 18', 'ASU Soccer vs. Utah — 7:00 PM', 'Tempe / Sun Devil Soccer Stadium', 'College Soccer', 'paid'],
    ['Sept. 18–20', "Pickin' in the Pines", 'Flagstaff / Pepsi Amphitheater', 'Music', 'paid'],
    ['Sept. 18–19', 'Southwest Flow Festival', 'Flagstaff / Various', 'Festival', 'paid'],
    ['Sept. 18–20', 'Sonoita Fair', 'Sonoita', 'Fair', 'tbd'],
    ['Sept. 19–Jan. 31', 'Desert Perspectives', 'Scottsdale / SMoCA', 'Art', 'paid'],
    ['Sept. 19–Jan. 31', 'Desert ArtLAB: What the Earth Keeps', 'Scottsdale / SMoCA', 'Art', 'paid'],
    ['Sept. 19', 'Arizona Diamondbacks vs. New York Yankees', 'Phoenix / Chase Field', 'Baseball', 'paid'],
    ['Sept. 19', 'Arizona Football vs. Northern Illinois', 'Tucson / Arizona Stadium', 'College Football', 'paid'],
    ['Sept. 19', 'Phoenix Rising FC vs. El Paso Locomotive FC', 'Phoenix / Phoenix Rising Stadium', 'Soccer', 'paid'],
    ['Sept. 19', 'Isaiah Falls', 'Phoenix / The Van Buren', 'Music', 'paid'],
    ['Sept. 19', 'On a Sunday Afternoon: Saturday Love', 'Phoenix / The Van Buren', 'Music', 'paid'],
    ['Sept. 19', 'Adaptive Fashion Show', 'Mesa / Mesa Arts Center', 'Arts', 'paid'],
    ['Sept. 19', 'Leslie Jones', 'Mesa / Mesa Arts Center', 'Comedy', 'paid'],
    ['Sept. 19–20', 'Payson Showdown', 'Payson', 'Rodeo/Sports', 'paid'],
    ['Sept. 19–20', 'Prescott Indian Art Market', 'Prescott / Sharlot Hall Museum', 'Arts/Culture', 'paid'],
    ['Sept. 19–20', 'Garlic Festival', 'Queen Creek / Schnepf Farms', 'Food', 'paid'],
    ['Sept. 19–20', 'Rio Rico Fall Festival & Pet Adoption Pop-Up', 'Rio Rico', 'Community', 'free'],
    ['Sept. 19–20', 'Oak Creek Arts & Craft Show', 'Sedona / Bell Rock Plaza', 'Arts', 'free'],
    ['Sept. 19–20', 'Gilbert Family Triathlon', 'Gilbert', 'Sports', 'paid'],
    ['Sept. 19', 'Scottsdale Saddle Club', 'Cave Creek / Memorial Arena Rodeo Grounds', 'Equestrian', 'paid'],
    ['Sept. 19', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
    ['Sept. 20', 'Arizona Diamondbacks vs. New York Yankees', 'Phoenix / Chase Field', 'Baseball', 'paid'],
    ['Sept. 20', 'Arizona Cardinals vs. Seattle Seahawks — 1:25 PM', 'Glendale / State Farm Stadium', 'NFL', 'paid'],
    ['Sept. 20', 'Alejandro Fernández', 'Phoenix / Arizona Financial Theatre', 'Music', 'paid'],
    ['Sept. 20', 'Jay Park', 'Phoenix / Arizona Financial Theatre', 'Music', 'paid'],
    ['Sept. 20', 'Paris Paloma', 'Phoenix / The Van Buren', 'Music', 'paid'],
    ['Sept. 20', 'Santa Cruz River Dragonfly Festival', 'Southern Arizona', 'Nature', 'free'],
    ['Sept. 20', "Pickin' in the Pines — final day", 'Flagstaff', 'Music', 'paid'],
    ['Sept. 21', 'Phoenix Mercury vs. Dallas Wings', 'Phoenix / Mortgage Matchup Center', 'WNBA', 'paid'],
    ['Sept. 22', 'Freya Skye', 'Phoenix / Arizona Financial Theatre', 'Music', 'paid'],
    ['Sept. 23–27', 'AZQHA Arizona Fall Championship', 'Scottsdale / WestWorld', 'Equestrian', 'paid'],
    ['Sept. 24', 'Phoenix Mercury vs. Las Vegas Aces', 'Phoenix / Mortgage Matchup Center', 'WNBA', 'paid'],
    ['Sept. 24', 'Rio Rico Community Center Fall Bingo Night', 'Rio Rico', 'Community', 'paid'],
    ['Sept. 24', 'Ballet Under the Stars', 'Fountain Hills', 'Dance', 'free'],
    ['Sept. 24', 'Desert Critters Discovery Station', 'Cave Creek', 'Nature', 'free'],
    ['Sept. 25–27', 'Prescott Highland Games', 'Prescott', 'Culture', 'paid'],
    ['Sept. 25–27', 'ACA Race #2 / Arizona HS Cycling Race', 'Prescott', 'Cycling', 'paid'],
    ['Sept. 25–Oct. 4', 'Festival of Science', 'Flagstaff', 'Science', 'free'],
    ['Sept. 25', 'SOUNDCHECK: Meat Puppets', 'Phoenix / Phoenix Art Museum', 'Music', 'paid'],
    ['Sept. 25', '¡Celebra! Hispanic Heritage Month Celebration', 'Casa Grande', 'Culture', 'free'],
    ['Sept. 25', '¡Viva! A Celebration of Hispanic Heritage', 'Gilbert', 'Culture', 'free'],
    ['Sept. 25', 'Scorpion Safari', 'Cave Creek', 'Nature', 'paid'],
    ['Sept. 25–27', 'Oak Creek Arts & Craft Show', 'Sedona', 'Arts', 'free'],
    ['Sept. 25–27', 'FoodieLand', 'Avondale / Phoenix Raceway', 'Food', 'paid'],
    ['Sept. 25–Jan. 17', 'ArtSpark #1', 'Scottsdale / SMoCA', 'Art', 'paid'],
    ['Sept. 26–Feb. 7', 'alejandro t. acierto: Model Home', 'Scottsdale / SMoCA', 'Art', 'paid'],
    ['Sept. 26–27', 'Tucson Fall Classic / WPRA Jackpot', 'Tucson', 'Rodeo', 'paid'],
    ['Sept. 26', 'Prescott All-Corvette Car Show', 'Prescott', 'Cars', 'tbd'],
    ['Sept. 26', 'Patagonia native-plant/community event', 'Patagonia', 'Nature/Community', 'free'],
    ['Sept. 26', "Tubac Jack's Annual Luau", 'Tubac', 'Food/Culture', 'paid'],
    ['Sept. 26–27', 'Scalia/Ginsburg', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Sept. 26', 'PHX Zine Fest', 'Phoenix / Rocket Space Gallery', 'Arts', 'tbd'],
    ['Sept. 26', 'Fly-In Breakfast', 'Casa Grande Municipal Airport', 'Aviation/Food', 'paid'],
    ['Sept. 26', '9/11 National Day of Service & Remembrance', 'Casa Grande', 'Community', 'free'],
    ['Sept. 26', 'Parks for Pollinators: BioBlitz', 'Gilbert', 'Nature', 'free'],
    ['Sept. 26', 'Manhattan Short Film Festival', 'Sedona', 'Film', 'paid'],
    ['Sept. 26', 'SIX the Musical LIVE!', 'Sedona', 'Theater', 'paid'],
    ['Sept. 26–27', 'SpiritFlow intensive', 'Sedona', 'Wellness', 'paid'],
    ['Sept. 26', 'Cowboys for Kids', 'Cave Creek', 'Community', 'paid'],
    ['Sept. 26', 'El Tour Loop de Loop', 'Tucson', 'Cycling', 'paid'],
    ['Sept. 27', 'Arizona Cardinals at San Francisco 49ers — 1:05 PM', "Santa Clara / Levi's Stadium", 'NFL', 'paid'],
    ['Sept. 27', 'Arizona Diamondbacks at San Diego Padres', 'San Diego / Petco Park', 'Baseball', 'paid'],
    ['Sept. 27', 'Scalia/Ginsburg', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Sept. 27', 'Prescott Highland Games — final day', 'Prescott', 'Culture', 'paid'],
    ['Sept. 27', 'ACA Race #2 — final day', 'Prescott', 'Cycling', 'paid'],
    ['Sept. 27–Oct. 17', 'Proof', 'Tucson / Invisible Theatre', 'Theater', 'paid'],
    ['Sept. 30', 'Films at PhxArt: The Social Network', 'Phoenix / Phoenix Art Museum', 'Film', 'paid'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
  ]),
  month('October 2026', [
    ['Oct. 1–Nov. 1', 'Arizona State Fair', 'Phoenix / State Fairgrounds', 'Fair', 'paid'],
    ['Oct. 1–Nov. 15', 'Arizona Fall League / Scottsdale Scorpions', 'Scottsdale / Scottsdale Stadium', 'Baseball', 'paid'],
    ['Oct. 1–3', 'Flagstaff Star Party', 'Flagstaff', 'Astronomy', 'mixed'],
    ['Oct. 1–4', 'Festival of Science', 'Flagstaff', 'Science', 'free'],
    ['Oct. 1', 'Arizona Opera Studio Series', 'Phoenix / Arizona Opera Center', 'Opera', 'paid'],
    ['Oct. 1', 'Concerts in the Park: Velvet Crush', 'Gilbert', 'Music', 'free'],
    ['Oct. 2–3', 'Arizona State Fair All Indian Rodeo', 'Phoenix', 'Rodeo', 'paid'],
    ['Oct. 2–3', 'Cruise to the Pines Car Show', 'Prescott', 'Cars', 'paid'],
    ['Oct. 2', 'First Peoples, First Friday', 'Phoenix / Herberger Theater Center', 'Culture', 'mixed'],
    ['Oct. 2', 'Ricardo Quevedo – Caer Con Estilo', 'Phoenix / Herberger Theater Center', 'Comedy', 'paid'],
    ['Oct. 2', 'The Umbilical Brothers: The Distraction', 'Phoenix / Herberger Theater Center', 'Comedy', 'paid'],
    ['Oct. 2', 'ASU Swimming & Diving vs. UNLV — 6:00 PM', 'Tempe', 'College Sports', 'paid'],
    ['Oct. 3', 'Arizona Football vs. Cincinnati', 'Tucson / Arizona Stadium', 'College Football', 'tbd'],
    ['Oct. 3–4', 'Final Symphony: Music from Final Fantasy', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['Oct. 3', 'Magic of Motown', 'Phoenix / Herberger Theater Center', 'Music', 'paid'],
    ['Oct. 3', 'Phoenix Rising FC', 'Phoenix', 'Soccer', 'tbd'],
    ['Oct. 3', 'Saddles 100 Trail Run', 'Prescott', 'Running', 'paid'],
    ['Oct. 3–4', 'Fall Arts & Craft Faire', 'Prescott', 'Arts', 'free'],
    ['Oct. 3', 'Flagstaff Oktoberfest', 'Flagstaff', 'Festival', 'paid'],
    ['Oct. 3', 'Barks & Brews', 'Flagstaff', 'Community', 'paid'],
    ['Oct. 3–4', 'Rex Allen Days Rodeo', 'Willcox', 'Rodeo', 'paid'],
    ['Oct. 3', 'Finer Arts Mimosas & Muffins', 'Cave Creek', 'Arts/Food', 'paid'],
    ['Oct. 3', 'USMNT vs. Mexico', 'Glendale / State Farm Stadium', 'Soccer', 'paid'],
    ['Oct. 3', 'ASU Football vs. Baylor', 'Tempe', 'College Football', 'tbd'],
    ['Oct. 4', 'ASU Volleyball vs. Iowa State', 'Tempe', 'College Sports', 'tbd'],
    ['Oct. 4', 'Arizona Cardinals at New York Giants — 10:00 AM', 'East Rutherford, NJ', 'NFL', 'paid'],
    ['Oct. 4', 'Dogtoberfest', 'Prescott', 'Community', 'free'],
    ['Oct. 4', 'Arizona State Fair Xtreme Bulls', 'Phoenix', 'Rodeo', 'paid'],
    ['Oct. 5–11', 'Best of the West & NRHA Southwest', 'Scottsdale / WestWorld', 'Equestrian', 'paid'],
    ['Oct. 6', 'BIG OCEAN – Fall 2026 Tour', 'Phoenix / Herberger Theater Center', 'Music', 'paid'],
    ['Oct. 8–11', 'Scottsdale Fashion Week', 'Scottsdale / Various', 'Fashion', 'paid'],
    ['Oct. 8–10', 'Arizona Ridge Riders / PBR Ridge Rider Days', 'Glendale / Desert Diamond Arena', 'Rodeo/Sports', 'paid'],
    ['Oct. 8', 'ASU Soccer vs. Iowa State — 7:00 PM', 'Tempe / Sun Devil Soccer Stadium', 'College Soccer', 'paid'],
    ['Oct. 9–11', 'Paolo Conducts Rachmaninoff & Prokofiev', 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Oct. 9–11', 'Four Peaks Oktoberfest', 'Tempe Town Lake', 'Festival', 'paid'],
    ['Oct. 9–11', 'Sonoita Quarter Horse Show', 'Sonoita', 'Equestrian', 'paid'],
    ['Oct. 9', 'Sound Bites Music & Food Festival', 'Gilbert Regional Park', 'Food/Music', 'paid'],
    ['Oct. 9–11', 'Oak Creek Arts & Craft Show', 'Sedona', 'Arts', 'free'],
    ['Oct. 9', 'ASU Hockey vs. Holy Cross — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Oct. 9', 'ASU Volleyball vs. Colorado — 7:00 PM', 'Tempe', 'College Sports', 'paid'],
    ['Oct. 10', "ASU Football vs. Hawai'i", 'Tempe', 'College Football', 'tbd'],
    ['Oct. 10', 'NAU Football vs. Montana', 'Flagstaff', 'College Football', 'paid'],
    ['Oct. 10', 'Whiskey Row Marathon', 'Prescott', 'Running', 'paid'],
    ['Oct. 10–11', 'Benson Butterfield Rodeo', 'Benson', 'Rodeo', 'paid'],
    ['Oct. 10–11', 'Patagonia Fall Festival', 'Patagonia', 'Festival', 'mixed'],
    ['Oct. 10', 'Beeline Cruise In Car Show', 'Payson', 'Cars', 'free'],
    ['Oct. 10', 'Phoenix Suns vs. San Antonio Spurs — 7:30 PM', 'Phoenix', 'NBA / Preseason', 'paid'],
    ['Oct. 10', 'Movie in the Park', 'Fountain Hills', 'Film', 'free'],
    ['Oct. 10', 'Movie in the Park', 'Litchfield Park', 'Film', 'free'],
    ['Oct. 10–11', 'Sedona Arts Festival', 'Sedona', 'Arts', 'paid'],
    ['Oct. 10', 'Cave Creek Car Show', 'Cave Creek', 'Cars', 'free'],
    ['Oct. 10–11', 'Phoenix Pride', 'Phoenix / Steele Indian School Park', 'Community', 'paid'],
    ['Oct. 10', 'ASU Hockey vs. Holy Cross — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Oct. 11', 'Arizona Cardinals vs. Detroit Lions — 1:25 PM', 'Glendale / State Farm Stadium', 'NFL', 'paid'],
    ['Oct. 11', 'ASU Soccer vs. Houston — Noon', 'Tempe', 'College Soccer', 'paid'],
    ['Oct. 11', 'ASU Volleyball vs. TCU', 'Tempe', 'College Sports', 'tbd'],
    ['Oct. 13', 'Arizona Opera Studio Series', 'Phoenix / Arizona Opera Center', 'Opera', 'paid'],
    ['Oct. 13', 'U.S. Navy 251st Anniversary Flag Raising', 'Litchfield Park', 'Military/Community', 'free'],
    ['Oct. 14–15', 'Taste of Cave Creek', 'Cave Creek', 'Food', 'paid'],
    ['Oct. 15', 'ASU Volleyball vs. Arizona — 7:00 PM', 'Tempe / Desert Financial Arena', 'College Sports', 'paid'],
    ['Oct. 15–18', 'Show Low Film Festival', 'Show Low', 'Film', 'paid'],
    ['Oct. 15', "Mendelssohn & Beethoven's 2nd Symphony", 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Oct. 15', 'Concerts in the Park: Poor Barbie', 'Gilbert', 'Music', 'free'],
    ['Oct. 16–18', 'NASCAR Weekend', 'Avondale / Phoenix Raceway', 'Racing', 'paid'],
    ['Oct. 16', 'Phoenix Suns vs. Utah Jazz — 7:00 PM', 'Phoenix', 'NBA / Preseason', 'paid'],
    ['Oct. 16–17', 'Great Gilbert Campout', 'Gilbert', 'Family/Outdoor', 'paid'],
    ['Oct. 16–24', 'Sedona Plein Air Festival', 'Sedona', 'Arts', 'paid'],
    ['Oct. 16–18', 'Tucson Meet Yourself', 'Tucson', 'Culture/Food', 'free'],
    ['Oct. 17', 'Scottsdale Fall Festival', 'Scottsdale Civic Center', 'Family/Festival', 'mixed'],
    ['Oct. 17', 'Phoenix Suns vs. Golden State Warriors', 'Phoenix', 'NBA', 'paid'],
    ['Oct. 17', 'Prescott Route 66 Centennial Auto Show', 'Prescott', 'Cars', 'free'],
    ['Oct. 17', 'Sacred Heart Catholic School Gala', 'Nogales', 'Community', 'paid'],
    ['Oct. 17', 'SYMPHONYFUSE: Mahler × Notorious B.I.G. × 2Pac', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['Oct. 17', 'Eva Ayllon with Daniela Darcourt', 'Phoenix / Herberger Theater Center', 'Music', 'paid'],
    ['Oct. 17', 'Pumpkin Dunk', 'Gilbert', 'Family', 'free'],
    ['Oct. 17', 'Great Pumpkin Splash!', 'Sedona', 'Family', 'paid'],
    ['Oct. 17', 'Fest of Fall', 'Sedona / Tlaquepaque', 'Festival', 'mixed'],
    ['Oct. 18', 'Arizona Cardinals at Los Angeles Rams — 1:05 PM', 'Inglewood, CA', 'NFL', 'paid'],
    ['Oct. 18', 'Arizona fall events/festivals', 'Statewide', 'Festivals', 'mixed'],
    ['Oct. 20–25', "The Who's Tommy", 'Tucson / Centennial Hall', 'Theater', 'paid'],
    ['Oct. 22', 'ASU Swimming & Diving vs. SMU — 2:00 PM', 'Tempe', 'College Sports', 'paid'],
    ['Oct. 22', 'ASU Soccer vs. Baylor — 7:00 PM', 'Tempe', 'College Soccer', 'paid'],
    ['Oct. 22', 'Concerts in the Park: Rylee Paige', 'Gilbert', 'Music', 'free'],
    ['Oct. 23–25', 'Man of La Mancha', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Oct. 23–25', 'Stagecoach Village Fine Art & Wine Festival', 'Cave Creek', 'Arts/Food', 'paid'],
    ['Oct. 24', 'ASU Football vs. Kansas State', 'Tempe', 'College Football', 'tbd'],
    ['Oct. 24', 'Phoenix Suns vs. Golden State Warriors — 7:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Oct. 24', 'Scottsdale Día de los Muertos', 'Old Town Scottsdale', 'Cultural Festival', 'mixed'],
    ['Oct. 24', 'Día de los Muertos Festival', 'Mesa / Mesa Arts Center', 'Culture', 'mixed'],
    ['Oct. 24', 'Flagstaff International Dark Sky City 25th Anniversary Celebration', 'Flagstaff', 'Astronomy', 'mixed'],
    ['Oct. 24–25', 'Celebraciones de la Gente', 'Flagstaff / Museum of Northern Arizona', 'Culture', 'paid'],
    ['Oct. 24', 'Rio Rico Historical Society Fall Bus Tour', 'Rio Rico', 'History', 'paid'],
    ['Oct. 24', 'Eek! at the Peak!', 'Phoenix / Pinnacle Peak Park', 'Family', 'free'],
    ['Oct. 24', 'Spooky Blast', 'Fountain Hills', 'Halloween', 'mixed'],
    ['Oct. 24', 'Movie in the Park', 'Litchfield Park', 'Film', 'free'],
    ['Oct. 25', 'ASU Soccer vs. Colorado — 1:00 PM', 'Tempe', 'College Soccer', 'paid'],
    ['Oct. 25', 'Arizona Cardinals vs. Denver Broncos — 1:05 PM', 'Glendale / State Farm Stadium', 'NFL', 'paid'],
    ['Oct. 25', "Dunkin' for Pumpkins", 'Fountain Hills', 'Family', 'free'],
    ['Oct. 27', 'Swan Lake: Symphony of Lights', 'Phoenix / Herberger Theater Center', 'Dance', 'paid'],
    ['Oct. 28–Nov. 3', 'Santa Cruz County Día de los Muertos Altar Tour', 'Nogales/Santa Cruz County', 'Culture', 'mixed'],
    ['Oct. 29', 'Concerts in the Park: Carly Klein', 'Gilbert', 'Music', 'free'],
    ['Oct. 30', 'ASU Soccer vs. Arizona — 7:00 PM', 'Tempe / Sun Devil Soccer Stadium', 'College Soccer', 'paid'],
    ['Oct. 30', 'ASU Volleyball vs. UCF — 7:00 PM', 'Tempe', 'College Sports', 'tbd'],
    ['Oct. 30', 'Phoenix Suns vs. Denver Nuggets — 7:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Oct. 30–Nov. 1', 'Pirates of the Caribbean: The Curse of the Black Pearl in Concert', 'Phoenix / Symphony Hall', 'Music/Film', 'paid'],
    ['Oct. 31', 'AIA Girls Fall Soccer State Championship', 'Gilbert / Williams Field HS', 'High School Sports', 'paid'],
    ['Oct. 31', 'Heroes & Villains: Music in Motion', 'Phoenix / Madison Center for the Arts', 'Music', 'paid'],
    ['Oct. 31', 'Halloween Trunk or Treat', 'Show Low', 'Family', 'free'],
    ['Oct. 31', 'Uptown Trick or Treat', 'Sedona', 'Halloween', 'free'],
    ['Oct. 31', 'Halloween / Heritage District Activities', 'Gilbert', 'Halloween', 'mixed'],
    ['Oct. 31', 'Halloween events', 'Statewide', 'Family/Holiday', 'mixed'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
  ]),
  month('November 2026', [
    ['Nov. 1', 'Arizona State Fair — final day', 'Phoenix', 'Fair', 'paid'],
    ['Nov. 1–30', 'Fountain Hills Hiking Challenge', 'Fountain Hills', 'Outdoor', 'free'],
    ['Nov. 1', 'Pirates of the Caribbean in Concert — final day', 'Phoenix / Symphony Hall', 'Music/Film', 'paid'],
    ['Nov. 1', 'Arizona Cardinals at Dallas Cowboys — 11:00 AM', 'Arlington, TX', 'NFL', 'paid'],
    ['Nov. 1', 'ASU Volleyball vs. Houston — 1:00 PM', 'Tempe', 'College Sports', 'paid'],
    ['Nov. 2', "ASU Women's Basketball vs. Jackson State — 5:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 2', "ASU Men's Basketball vs. East Tennessee State — 8:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 3–7', 'AIA Swimming & Diving — Boys Divisions I–III', 'Arizona', 'High School Sports', 'paid'],
    ['Nov. 4', 'Phoenix Suns vs. Portland Trail Blazers — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Nov. 4–7', 'AIA Swimming & Diving — Girls Divisions I–III', 'Arizona', 'High School Sports', 'paid'],
    ['Nov. 5', 'Phoenix Suns vs. Orlando Magic — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Nov. 5', "ASU Women's Basketball vs. Northern Arizona — 6:30 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 5', 'The Three Brides', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Nov. 5–7', 'Turquoise Circuit ProRodeo', 'Cave Creek', 'Rodeo', 'paid'],
    ['Nov. 6–15', 'Canal Convergence: Western Nature', 'Scottsdale Waterfront', 'Public Art/Festival', 'free'],
    ['Nov. 6–8', "Beethoven's 7th Symphony & Chopin's 2nd Piano Concerto", 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Nov. 6–29', 'National Parks Exhibit', 'Phoenix / Herberger Theater Art Galleries', 'Art', 'free'],
    ['Nov. 6–29', 'Freedom Exhibit', 'Phoenix / Herberger Theater Art Galleries', 'Art', 'free'],
    ['Nov. 6', 'ASU Hockey vs. Denver — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Nov. 6', "ASU Men's Basketball vs. Northern Colorado — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 6–8', 'All Souls Procession weekend', 'Tucson', 'Culture', 'mixed'],
    ['Nov. 7', 'ASU Football vs. Colorado', 'Tempe', 'College Football', 'tbd'],
    ['Nov. 7', 'Phoenix Suns vs. Houston Rockets — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Nov. 7', 'AIA Volleyball championships / qualifying', 'Arizona', 'High School Sports', 'paid'],
    ['Nov. 7–8', 'Scottsdale Italian Festival', 'Scottsdale Civic Center', 'Italian Food/Culture/Wine', 'paid'],
    ['Nov. 7–8', 'YumaCon', 'Yuma', 'Pop Culture', 'paid'],
    ['Nov. 7', 'Cowboy Festival', 'Empire Ranch/Sonoita', 'Western', 'mixed'],
    ['Nov. 7', 'Tubac Día de los Muertos celebration', 'Tubac', 'Culture', 'mixed'],
    ['Nov. 7', 'Bentley Scottsdale Polo Championships', 'Scottsdale / WestWorld', 'Polo/Social/Sports', 'paid'],
    ['Nov. 7', 'Diwali: Festival of Lights', 'Chandler', 'Culture', 'mixed'],
    ['Nov. 7–8', 'El Gato con Botas', 'Phoenix', 'Theater', 'paid'],
    ['Nov. 7', 'Litchfield Park Festival of Arts', 'Litchfield Park', 'Arts', 'free'],
    ['Nov. 7', 'Arizona Fall Festival', 'Phoenix area', 'Food/Festival', 'free'],
    ['Nov. 7–8', 'Autumnfest', 'Anthem', 'Arts/Festival', 'free'],
    ['Nov. 8', 'ASU Hockey vs. Denver — Noon', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Nov. 8', 'ASU Volleyball vs. Utah — 1:00 PM', 'Tempe', 'College Sports', 'paid'],
    ['Nov. 8', 'Arizona Cardinals at Seattle Seahawks — 2:25 PM', 'Seattle, WA', 'NFL', 'paid'],
    ['Nov. 8', 'Wings & Wheels', 'Nogales', 'Aviation', 'paid'],
    ['Nov. 9', 'Phoenix Suns vs. San Antonio Spurs — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Nov. 10', 'Phoenix Suns vs. LA Clippers — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Nov. 10', "ASU Men's Basketball vs. Hofstra — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 10–15', 'Elf the Musical', 'Tucson / Centennial Hall', 'Theater', 'paid'],
    ['Nov. 11', 'Prescott Veterans Day Parade', 'Prescott', 'Community', 'free'],
    ['Nov. 11–15', 'Fleurs de Villes NOËL', 'Scottsdale Fashion Square', 'Floral/Art', 'mixed'],
    ['Nov. 12', 'Phoenix Suns vs. Charlotte Hornets — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Nov. 12', 'Good Morning Yuma', 'Yuma Civic Center', 'Community', 'free'],
    ['Nov. 12', "Brahms' Serenade No. 1", 'Phoenix / Musical Instrument Museum', 'Classical', 'paid'],
    ['Nov. 13', "ASU Men's Basketball vs. ULM — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 13–14', "Show Low Santa's North Pole Workshop & Craft Fair", 'Show Low', 'Holiday', 'paid'],
    ['Nov. 13–15', 'The Play That Goes Wrong', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Nov. 13–15', 'Music of the Knights', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['Nov. 13–15', 'Hondo Rodeo Fest', 'Phoenix / Chase Field', 'Rodeo', 'paid'],
    ['Nov. 13–15', 'Fountain Festival of Fine Art & Crafts', 'Fountain Hills', 'Arts', 'free'],
    ['Nov. 13–14', 'DUSK X', 'Tucson', 'Music', 'paid'],
    ['Nov. 13–15', 'Gem & Mineral Thanksgiving Showcase', 'Tucson', 'Gems', 'mixed'],
    ['Nov. 14', 'NAU Football vs. Weber State', 'Flagstaff', 'College Football', 'paid'],
    ['Nov. 14', 'AIA Cross Country State Championships', 'Cave Creek', 'High School Sports', 'paid'],
    ['Nov. 14', 'AIA Girls Volleyball State Championships', 'Arizona', 'High School Sports', 'paid'],
    ['Nov. 14', 'Arizona Football vs. TCU', 'Tucson / Arizona Stadium', 'College Football', 'tbd'],
    ['Nov. 14', "Ridin' For a Cure", 'Prescott', 'Community', 'paid'],
    ['Nov. 14', "Arizona Wine Founder's Day", 'Sonoita', 'Food/Wine', 'paid'],
    ['Nov. 14', 'Festival of the Arts', 'Phoenix / Herberger Theater Center', 'Arts', 'paid'],
    ['Nov. 14', 'Pride in Chandler', 'Chandler', 'Community', 'mixed'],
    ['Nov. 14', 'Cave Creek Cactus Classic', 'Cave Creek', 'Sports', 'paid'],
    ['Nov. 14', 'Desert Discovery Day', 'Cave Creek', 'Nature', 'free'],
    ['Nov. 15', 'Phoenix Suns vs. Los Angeles Lakers — 1:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Nov. 15', "ASU Women's Basketball vs. Penn State — 2:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 15', 'Arizona Cardinals vs. Los Angeles Rams — 2:05 PM', 'Glendale / State Farm Stadium', 'NFL', 'paid'],
    ['Nov. 17', "ASU Women's Basketball vs. San Diego — 6:30 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 18', "ASU Men's Basketball vs. Oakland — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 20–22', 'Muñoz Conducts Schumann & Barber', 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Nov. 20–22', 'Gilbert Days Weekend', 'Gilbert', 'Festival', 'mixed'],
    ['Nov. 20–22', 'Hidden in the Hills Artist Studio Tour', 'Scottsdale/Cave Creek area', 'Arts', 'free'],
    ['Nov. 20', "ASU Women's Basketball vs. Santa Clara — 6:30 PM", 'Tempe / Mullett Arena', 'College Basketball', 'paid'],
    ['Nov. 21', 'ASU Football vs. Oklahoma State', 'Tempe', 'College Football', 'tbd'],
    ['Nov. 21', 'NAU Football vs. Northern Colorado', 'Flagstaff', 'College Football', 'paid'],
    ['Nov. 21', 'AIA Football semifinals', 'Arizona', 'High School Sports', 'paid'],
    ['Nov. 21', 'AIA Flag Football championships', 'Arizona', 'High School Sports', 'paid'],
    ['Nov. 21', 'Turkey Trot & Turkey Bowl', 'Payson', 'Sports', 'free'],
    ['Nov. 21', 'Special Olympics Tucson Field of Dreams', 'Tucson', 'Sports', 'free'],
    ['Nov. 21', 'Arizona Indigenous Culinary Experience', 'Scottsdale', 'Food/Culture', 'paid'],
    ['Nov. 21', 'From Gershwin to Garland', 'Phoenix / Herberger Theater Center', 'Music', 'paid'],
    ['Nov. 21', 'Southwest Tea', 'Chandler', 'Food', 'paid'],
    ['Nov. 21', 'Gilbert Days Parade', 'Gilbert', 'Parade', 'free'],
    ['Nov. 21', 'Gilbert Days Festival', 'Gilbert', 'Festival', 'mixed'],
    ['Nov. 21', 'Free To Be Me Drumming', 'Sedona', 'Music/Community', 'free'],
    ['Nov. 21', 'El Tour de Tucson', 'Tucson', 'Cycling', 'paid'],
    ['Nov. 22', 'Arizona Cardinals at Kansas City Chiefs — 11:00 AM', 'Kansas City, MO', 'NFL', 'paid'],
    ['Nov. 22', 'Special Olympics Lower River Area Golf Competition', 'Yuma', 'Sports', 'free'],
    ['Nov. 22', 'Gilbert Days Weekend', 'Gilbert', 'Festival', 'mixed'],
    ['Nov. 22', 'Hidden in the Hills Artist Studio Tour', 'Arizona', 'Arts', 'free'],
    ['Nov. 24', "ASU Women's Basketball vs. San Jose State — 6:30 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 25', 'ASU Volleyball vs. Kansas State — 7:00 PM', 'Tempe', 'College Sports', 'paid'],
    ['Nov. 26', 'Turkey Trot & Thanksgiving Parade', 'Fountain Hills', 'Holiday/Sports', 'free'],
    ['Nov. 26', 'Turkey Trot', 'Sedona', 'Running', 'paid'],
    ['Nov. 27', 'Phoenix Suns vs. Dallas Mavericks — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Nov. 27', 'ASU Volleyball vs. Kansas — 7:00 PM', 'Tempe', 'College Sports', 'paid'],
    ['Nov. 27', 'ASU Hockey vs. Alaska Anchorage — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Nov. 27–29', 'Elf in Concert', 'Phoenix / Symphony Hall', 'Music/Film', 'paid'],
    ['Nov. 27', 'Hidden in the Hills Artist Studio Tour — second weekend', 'Arizona', 'Arts', 'free'],
    ['Nov. 27', 'Sedona Turkey Trot', 'Sedona', 'Running', 'paid'],
    ['Nov. 28', "ASU Women's Basketball vs. CSU Bakersfield — 2:30 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 28', 'ASU Hockey vs. Alaska Anchorage — 5:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Nov. 28', 'AIA Open Football semifinal', 'Arizona', 'High School Sports', 'paid'],
    ['Nov. 28', 'AIA 2A/3A Football championships', 'Arizona', 'High School Sports', 'tbd'],
    ['Nov. 28', 'Prescott Holiday Light Parade', 'Prescott', 'Holiday', 'free'],
    ['Nov. 28–Dec. 20', 'Little Shop of Horrors', 'Tucson / Invisible Theatre', 'Theater', 'paid'],
    ['Nov. 28–Dec. 31', 'Scottsdazzle', 'Scottsdale / Old Town & Waterfront', 'Holiday', 'mixed'],
    ['Nov. 29', "ASU Women's Basketball vs. Wake Forest — 12:30 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 29', 'Arizona Cardinals vs. Washington Commanders — 2:25 PM', 'Glendale / State Farm Stadium', 'NFL', 'paid'],
    ['Nov. 30', "ASU Men's Basketball vs. Montana — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Nov. 30', 'Water Tower Holiday Lighting', 'Gilbert', 'Holiday', 'free'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
  ]),
  month('December 2026', [
    ['Dec. 1', 'Phoenix Suns vs. LA Clippers — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Dec. 2', 'Phoenix Suns vs. Sacramento Kings — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Dec. 2–3', 'Days Off', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Dec. 4', 'ASU Hockey vs. Colorado College — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Dec. 4', 'AIA 4A Football State Championship', 'Arizona', 'High School Sports', 'tbd'],
    ['Dec. 4', 'AIA 5A Football State Championship', 'Arizona', 'High School Sports', 'tbd'],
    ['Dec. 4–5', 'Tubac Center of the Arts holiday events', 'Tubac', 'Arts/Holiday', 'mixed'],
    ['Dec. 4–6', 'Holiday Pops Spectacular', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['Dec. 4–6', 'Hadestown', 'Tucson / Centennial Hall', 'Broadway', 'paid'],
    ['Dec. 5', 'ASU Hockey vs. Colorado College — 5:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Dec. 5', 'AIA 6A Football State Championship', 'Arizona', 'High School Sports', 'tbd'],
    ['Dec. 5', 'AIA Open Division Football State Championship', 'Arizona', 'High School Sports', 'tbd'],
    ['Dec. 5', "GCU Men's Basketball vs. Santa Clara", 'Phoenix / Global Credit Union Arena', 'College Basketball', 'paid'],
    ['Dec. 5', 'Prescott Christmas Parade & Courthouse events', 'Prescott', 'Holiday', 'free'],
    ['Dec. 4–5', 'Tubac Luminarias', 'Tubac', 'Holiday', 'mixed'],
    ['Dec. 5', 'Arizona Korean Culture Festival', 'Chandler', 'Culture', 'free'],
    ['Dec. 5', 'Breakfast with Santa', 'Sedona', 'Family', 'paid'],
    ['Dec. 6', "ASU Women's Basketball vs. Gonzaga — 2:00 PM", 'Tempe / Mullett Arena', 'College Basketball', 'paid'],
    ['Dec. 6', 'Arizona Cardinals vs. Philadelphia Eagles — 2:05 PM', 'Glendale / State Farm Stadium', 'NFL', 'paid'],
    ['Dec. 6', 'Patagonia Benderly Concert Series', 'Patagonia', 'Music', 'paid'],
    ['Dec. 8', "ASU Women's Basketball vs. UTRGV — 5:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Dec. 8', "ASU Men's Basketball vs. Mercer — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Dec. 9–13', "Handel's Messiah", 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Dec. 10–20', 'Claus & Effect: An Elf Union Reunion', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Dec. 11', 'ASU Hockey vs. Western Michigan — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Dec. 11–13', 'Tucson Fourth Avenue Street Fair / Winter Street Fair', 'Tucson / Fourth Avenue', 'Arts/Shopping', 'free'],
    ['Dec. 11–22', 'Riparian After Dark', 'Gilbert', 'Holiday', 'paid'],
    ['Dec. 11', 'Prescott Acker Night Musical Showcase', 'Prescott', 'Music/Holiday', 'free'],
    ['Dec. 12', 'ASU Hockey vs. Western Michigan — 5:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Dec. 12', 'Phoenix Suns vs. Minnesota Timberwolves — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Dec. 12', 'Christmas at Empire Ranch', 'Sonoita', 'Holiday', 'mixed'],
    ['Dec. 12', 'Walk4Unity — UN Human Rights Day', 'Chandler', 'Community', 'free'],
    ['Dec. 13', "Arizona Women's Basketball vs. Northern Arizona", 'Tucson / McKale Center', 'College Basketball', 'paid'],
    ['Dec. 13', 'Tucson Marathon', 'Tucson', 'Running', 'paid'],
    ['Dec. 13', 'Patagonia Benderly Concert Series', 'Patagonia', 'Music', 'paid'],
    ['Dec. 14', 'Phoenix Suns vs. Atlanta Hawks — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Dec. 18–20', 'Holiday Baroque', 'Phoenix / Orpheum Theatre', 'Classical', 'paid'],
    ['Dec. 18', 'Finer Arts Art Affaire', 'Cave Creek', 'Arts', 'paid'],
    ['Dec. 18', 'Luminaria Walk at Harmony Hollow', 'Cave Creek', 'Holiday', 'mixed'],
    ['Dec. 19', 'Cave Creek Santa Summit', 'Cave Creek', 'Family', 'free'],
    ['Dec. 19', 'Cave Creek Christmas Tractor Parade', 'Cave Creek', 'Holiday', 'free'],
    ['Dec. 19', 'Holiday Magic at Tlaquepaque', 'Sedona', 'Holiday', 'free'],
    ['Dec. 20', 'Arizona Cardinals vs. New York Jets — 2:05 PM', 'Glendale / State Farm Stadium', 'NFL', 'paid'],
    ['Dec. 20', "ASU Men's Basketball vs. San Diego — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Dec. 23', 'Phoenix Suns vs. Indiana Pacers — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Dec. 23', "ASU Men's Basketball vs. Idaho — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Dec. 26', 'Rate Bowl', 'Phoenix / Chase Field', 'College Football', 'paid'],
    ['Dec. 27', 'Arizona Cardinals at New Orleans Saints — 11:00 AM', 'New Orleans, LA', 'NFL', 'paid'],
    ['Dec. 28', 'Phoenix Suns vs. Golden State Warriors — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Dec. 29', "ASU Men's Basketball vs. Southern Illinois — 7:00 PM", 'Tempe', 'College Basketball', 'paid'],
    ['Dec. 30', 'Fiesta Bowl', 'Glendale / State Farm Stadium', 'College Football', 'paid'],
    ['Dec. 30', 'Phoenix Suns vs. Philadelphia 76ers — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Dec. 31', 'Phoenix Suns vs. New York Knicks — 6:00 PM', 'Phoenix', 'NBA', 'tbd'],
    ['Dec. 31', "New Year's Eve Gala: Havana Nights", 'Phoenix / Arizona Biltmore', 'Holiday', 'paid'],
    ['Dec. 31', 'Whiskey Row Boot Drop', 'Prescott', 'Holiday', 'mixed'],
    ['December', 'Holiday events / performances', 'Scottsdale Arts', 'Performing Arts', 'paid'],
    ['December', 'ZooLights', 'Phoenix Zoo', 'Holiday Lights', 'paid'],
    ['December — TBD', 'Las Noches de las Luminarias', 'Phoenix / Desert Botanical Garden', 'Holiday', 'paid'],
    ['December — TBD', 'Electric Light Parade', 'Casa Grande', 'Holiday', 'mixed'],
    ['December — TBD', 'Grande Glitters', 'Casa Grande', 'Holiday', 'mixed'],
    ['December — TBD', 'Christmas in the Park', 'Litchfield Park', 'Holiday', 'free'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
  ]),
  month('January 2027', [
    ['Jan. 1–10', 'Tyson Wells Rock & Gem Show', 'Quartzsite', 'Gems/Market', 'free'],
    ['Jan. 2', 'Phoenix Suns vs. Sacramento Kings — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Jan. 2', 'Finer Arts Mimosas & Muffins', 'Cave Creek', 'Arts/Food', 'paid'],
    ['Jan. 3', 'Arizona Cardinals vs. Las Vegas Raiders — 2:05 PM', 'Glendale / State Farm Stadium', 'NFL', 'paid'],
    ['Jan. 4', 'Phoenix Suns vs. Boston Celtics — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Jan. 7', 'Arizona Opera Studio Series', 'Phoenix / Arizona Opera Center', 'Opera', 'paid'],
    ['Jan. 8–10', 'Quartzsite RV/Swap Meet season', 'Quartzsite', 'Shopping/RV', 'free'],
    ['Jan. 8–10', 'Cave Creek Winter Fine Art & Wine Festival', 'Cave Creek', 'Arts/Food', 'paid'],
    ['Jan. 9', 'ASU Swimming & Diving vs. Grand Canyon — Noon', 'Tempe', 'College Sports', 'paid'],
    ['Jan. 9–10', 'Litchfield Park Gathering — Native American Fine Arts Festival', 'Litchfield Park', 'Arts/Culture', 'free'],
    ['Jan. 10', 'Phoenix Suns vs. Chicago Bulls — 4:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Jan. 15', 'ASU Hockey vs. Minnesota Duluth — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Jan. 15–17', 'Arizona Balloon Classic', 'Chandler / Wild Horse Pass', 'Festival', 'paid'],
    ['Jan. 15–17', 'Winter art festivals', 'Phoenix metro', 'Arts', 'mixed'],
    ['Jan. 15', 'Chandler Dr. Martin Luther King Jr. Awards Ceremony', 'Chandler', 'Community', 'free'],
    ['Jan. 15–17', 'Bruch & Mendelssohn with Rolf Haas', 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Jan. 15', 'Finer Arts Art Affaire', 'Cave Creek', 'Arts', 'paid'],
    ['Jan. 16', 'ASU Hockey vs. Minnesota Duluth — 5:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Jan. 16–Mar. 28', 'Celebration of Fine Art', 'Scottsdale / Big White Tents', 'Fine Art', 'paid'],
    ['Jan. 16', 'Tucson Polar Plunge', 'Tucson', 'Sports', 'paid'],
    ['Jan. 16', 'Arizona Archaeological Society – Rim Country', 'Payson', 'Archaeology', 'paid'],
    ['Jan. 16', 'Chandler Multicultural Festival', 'Chandler', 'Culture', 'free'],
    ['Jan. 20', 'Phoenix Suns vs. Memphis Grizzlies — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Jan. 21', 'Sonoran Sunset Series', 'Chandler', 'Music', 'free'],
    ['Jan. 22', 'Phoenix Suns vs. Utah Jazz — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Jan. 22–Feb. 7', 'The Vagina Monologues', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Jan. 22–24', 'E.T. in Concert', 'Phoenix / Orpheum Theatre', 'Music/Film', 'paid'],
    ['Jan. 22–24', 'Fine Art & Wine Festival', 'Cave Creek / Stagecoach Village', 'Arts/Food', 'paid'],
    ['Jan. 23–31', 'Barrett-Jackson Scottsdale Auction', 'Scottsdale / WestWorld', 'Collector Cars', 'paid'],
    ['Jan. 23', 'Carnival of Creatures: Past & Present', 'Phoenix / Madison Center for the Arts', 'Arts', 'paid'],
    ['Jan. 23', 'Embracing Wellness Community Expo', 'Chandler', 'Community', 'free'],
    ['Jan. 24', 'Phoenix Suns vs. Utah Jazz — 1:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Jan. 24–28', 'AMSPC Annual Meeting', 'Tucson', 'Conference', 'paid'],
    ['Jan. 24–Feb. 14', 'Vintage Hitchcock', 'Tucson / Invisible Theatre', 'Theater', 'paid'],
    ['Jan. 27–Feb. 14', 'Tucson Gem, Mineral & Fossil Showcase', 'Tucson / Multiple venues', 'Gems', 'mixed'],
    ['Jan. 28', 'Warlock, Charles & Elfman', 'Phoenix / Musical Instrument Museum', 'Music', 'paid'],
    ['Jan. 29–31', 'The Music of Paul Simon', 'Phoenix / Orpheum Theatre', 'Music', 'paid'],
    ['Jan. 30–31', 'The Pirates of Penzance', 'Phoenix / Symphony Hall', 'Theater', 'paid'],
    ['Jan. 31–Feb. 4', 'AGTA GemFair', 'Tucson Convention Center', 'Gems/Trade', 'paid'],
    ['Jan. 31–Feb. 20', 'The Play That Goes Wrong', 'Tucson / Arizona Theatre Company', 'Theater', 'paid'],
    ['Jan. 31', 'Skateboard Classic', 'Fountain Hills', 'Sports', 'free'],
    ['Saturdays', 'Old Town Scottsdale Farmers Market', 'Scottsdale / Old Town', 'Farmers Market', 'free'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
    ['January — TBD', 'Tucson Jazz Festival', 'Tucson', 'Music', 'paid'],
    ['January — TBD', "ASU Men's Basketball — Big 12 home games", 'Tempe', 'College Basketball', 'paid'],
    ['January — TBD', "Arizona Men's/Women's Basketball", 'Tucson', 'College Basketball', 'paid'],
    ['January — TBD', "NAU Men's/Women's Basketball", 'Flagstaff', 'College Basketball', 'paid'],
    ['January — TBD', "GCU Men's/Women's Basketball", 'Phoenix', 'College Basketball', 'paid'],
    ['January — TBD', 'Phoenix Suns home games', 'Phoenix', 'NBA', 'paid'],
    ['January — TBD', 'AIA winter sports championships/playoffs', 'Arizona', 'High School Sports', 'paid'],
  ]),
  month('February 2027', [
    ['Feb. 2–7', 'The Outsiders', 'Tucson / Centennial Hall', 'Broadway', 'paid'],
    ['Feb. 3', 'Phoenix Suns vs. Cleveland Cavaliers — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Feb. 4', 'Savor the Symphony', 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Feb. 5', 'Phoenix Suns vs. Houston Rockets — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Feb. 5–7', "John Williams' Epic 95th Birthday Celebration", 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Feb. 6', 'ASU Swimming & Diving vs. Arizona — Noon', 'Tempe', 'College Sports', 'paid'],
    ['Feb. 6', 'RunSedona Half Marathon / 10K / 5K / Walk', 'Sedona', 'Running', 'paid'],
    ['Feb. 6', 'Finer Arts Mimosas & Muffins', 'Cave Creek', 'Arts/Food', 'paid'],
    ['Feb. 8', 'Phoenix Suns vs. Los Angeles Lakers — 6:30 PM', 'Phoenix', 'NBA', 'paid'],
    ['Feb. 8–14', 'WM Phoenix Open', 'Scottsdale / TPC Scottsdale', 'Golf', 'paid'],
    ['Feb. 9', 'Arizona Opera Studio Series', 'Phoenix / Arizona Opera Center', 'Opera', 'paid'],
    ['Feb. 10', 'Phoenix Suns vs. Detroit Pistons — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Feb. 10–14', 'Tubac Festival of the Arts', 'Tubac', 'Arts', 'paid'],
    ['Feb. 11–21', 'Scottsdale Arabian Horse Show', 'Scottsdale / WestWorld', 'Equestrian', 'paid'],
    ['Feb. 12', 'ASU Hockey vs. North Dakota — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Feb. 12–14', 'Gold Rush Days', 'Wickenburg', 'Western', 'mixed'],
    ['Feb. 13', 'ASU Hockey vs. North Dakota — 5:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Feb. 18', 'Desert Foothills Land Trust Movie Night: Hummingbirds', 'Cave Creek', 'Film/Nature', 'paid'],
    ['Feb. 18', 'Arizona Archaeological Society – Rim Country', 'Payson', 'Archaeology', 'paid'],
    ['Feb. 19–21', 'NBA All-Star Weekend', 'Phoenix', 'Basketball', 'paid'],
    ['Feb. 19–21', 'The Bodyguard', 'Tucson / Centennial Hall', 'Broadway', 'paid'],
    ['Feb. 19–21', 'Paolo, Pablo & The Rite of Spring', 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Feb. 19', 'Teen Takeover', 'Fountain Hills', 'Youth/Community', 'free'],
    ['Feb. 19', 'Finer Arts Art Affaire', 'Cave Creek', 'Arts', 'paid'],
    ['Feb. 20–28', 'La Fiesta de los Vaqueros / Tucson Rodeo', 'Tucson', 'Rodeo', 'paid'],
    ['Feb. 20', 'Chandler Innovation Fair', 'Chandler', 'Science/Innovation', 'free'],
    ['Feb. 20–21', 'Navajo Rug & Jewelry Show', 'Cave Creek', 'Arts/Culture', 'paid'],
    ['Feb. 26', 'ASU Hockey vs. Omaha — 7:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Feb. 26–28', 'Cirque Adventure with Troupe Vertigo', 'Phoenix / Orpheum Theatre', 'Circus', 'paid'],
    ['Feb. 26–28', 'Fountain Festival of Fine Art & Crafts', 'Fountain Hills', 'Arts', 'free'],
    ['Feb. 27', 'Phoenix Suns vs. New Orleans Pelicans — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Feb. 27', 'ASU Hockey vs. Omaha — 5:00 PM', 'Tempe / Mullett Arena', 'College Hockey', 'paid'],
    ['Feb. 27', 'Clap, Count, Play! A Symphony Rhythm Party', 'Phoenix / Madison Center for the Arts', 'Music/Family', 'paid'],
    ['Feb. 27–Mar. 14', 'The Play That Goes Wrong', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Feb. 28', 'NBA All-Star Weekend — final day', 'Phoenix', 'Basketball', 'paid'],
    ['Feb. 28', 'Tucson Rodeo — final day', 'Tucson', 'Rodeo', 'paid'],
    ['Feb. 28', 'Cirque Adventure — final day', 'Phoenix', 'Circus', 'paid'],
    ['February', 'Scottsdale Western Week', 'Scottsdale / Old Town & Civic Center', 'Western/Cultural', 'mixed'],
    ['February', "Parada del Sol / Trail's End Festival", 'Scottsdale / Old Town', 'Western Parade/Festival', 'mixed'],
    ['February — TBD', 'Phoenix Chinese Week', 'Phoenix', 'Culture', 'mixed'],
    ['February — TBD', 'Arizona Matsuri', 'Phoenix', 'Culture', 'free'],
    ['February — TBD', 'Devour Culinary Classic', 'Phoenix', 'Food', 'paid'],
    ['February — TBD', 'Arizona Renaissance Festival', 'Gold Canyon', 'Festival', 'paid'],
    ['February — TBD', '24 Hours in the Old Pueblo', 'Tucson area', 'Mountain Bike', 'paid'],
    ['February — TBD', 'Cactus League Spring Training', 'Phoenix metro', 'Baseball', 'paid'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
  ]),
  month('March 2027', [
    ['Mar. 1', 'Phoenix Suns vs. Washington Wizards — 6:30 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 3', 'Phoenix Suns vs. Brooklyn Nets — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 5', 'Phoenix Suns vs. Minnesota Timberwolves — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 5–7', 'Sonoran Fine Art & Wine Festival', 'Cave Creek', 'Arts/Food', 'paid'],
    ['Mar. 5–7', 'Midnight at the Oasis', 'Yuma / Desert Sun Stadium', 'Cars/Music', 'paid'],
    ['Mar. 6–7', 'La Traviata', 'Phoenix / Symphony Hall', 'Opera', 'paid'],
    ['Mar. 6', 'Gilbert Global Village Festival', 'Gilbert', 'Culture', 'free'],
    ['Mar. 6', 'Spring Art & Wine Festival', 'Litchfield Park', 'Arts/Food', 'free'],
    ['Mar. 6', 'Finer Arts Mimosas & Muffins', 'Cave Creek', 'Arts/Food', 'paid'],
    ['Mar. 7–28', 'Murder For Two', 'Tucson / Invisible Theatre', 'Theater', 'paid'],
    ['Mar. 10–21', 'The Lion King', 'Tucson / Centennial Hall', 'Broadway', 'paid'],
    ['Mar. 11–13', 'ASU Softball vs. BYU', 'Tempe', 'College Softball', 'tbd'],
    ['Mar. 12–14', 'Katharina Conducts Prokofiev / Joyce Yang', 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Mar. 12–14', 'M3F Music Festival', 'Phoenix / Margaret T. Hance Park', 'Music', 'paid'],
    ['Mar. 12–14', 'Tempe Festival of the Arts', 'Tempe', 'Arts', 'free'],
    ['Mar. 13–14', 'Art at the Lake', 'Lake Havasu City', 'Arts', 'free'],
    ['Mar. 13', "St. Patrick's Parade", 'Sedona', 'Parade', 'free'],
    ['Mar. 13', 'Irish Fest', 'Fountain Hills', 'Culture/Music', 'free'],
    ['Mar. 18', 'Mendelssohn, Mozart & Haydn', 'Phoenix / Musical Instrument Museum', 'Classical', 'paid'],
    ['Mar. 19', 'Phoenix Suns vs. Miami Heat — 7:30 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 19', 'Redhouse Family Jazz Band', 'Tubac', 'Music', 'paid'],
    ['Mar. 19', 'Finer Arts Art Affaire', 'Cave Creek', 'Arts', 'paid'],
    ['Mar. 19–21', 'Top Gun: Maverick in Concert', 'Phoenix / Symphony Hall', 'Music/Film', 'paid'],
    ['Mar. 19–21', 'Art at Frontier Town', 'Cave Creek', 'Arts', 'free'],
    ['Mar. 20', 'Arizona Archaeological Society – Rim Country', 'Payson', 'Archaeology', 'paid'],
    ['Mar. 20', 'Cave Creek Rodeo Days Parade', 'Cave Creek', 'Parade', 'free'],
    ['Mar. 20', 'Cornhole Tournament', 'Cave Creek', 'Sports', 'paid'],
    ['Mar. 20', 'Eggstravaganza', 'Fountain Hills', 'Family', 'free'],
    ['Mar. 20', 'Touch-a-Truck', 'Fountain Hills', 'Family', 'free'],
    ['Mar. 21', 'Phoenix Suns vs. Portland Trail Blazers — 2:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 21', "Mutton Bustin' Qualifying Round", 'Cave Creek', 'Rodeo', 'paid'],
    ['Mar. 23', 'Phoenix Suns vs. Oklahoma City Thunder — 8:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 23', 'Arizona Opera Studio Series', 'Phoenix / Arizona Opera Center', 'Opera', 'paid'],
    ['Mar. 24', 'Phoenix Suns vs. Oklahoma City Thunder — 7:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 24', 'All Bulls, All Night!', 'Cave Creek', 'Rodeo', 'paid'],
    ['Mar. 25–27', "ASU Women's Golf — PING Invitational", 'Arizona', 'College Golf', 'paid'],
    ['Mar. 25–27', 'ASU Baseball vs. UCF', 'Tempe', 'College Baseball', 'tbd'],
    ['Mar. 25', 'Cave Creek Rodeo — First PRCA Performance', 'Cave Creek', 'Rodeo', 'paid'],
    ['Mar. 26', 'Phoenix Suns vs. Milwaukee Bucks — 7:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 26', 'Cave Creek Rodeo — Second PRCA Performance', 'Cave Creek', 'Rodeo', 'paid'],
    ['Mar. 26–28', 'ASU Softball vs. Arizona', 'Tempe', 'College Softball', 'tbd'],
    ['Mar. 27', "Cave Creek Rodeo — Final Performance & Mutton Bustin' Finals", 'Cave Creek', 'Rodeo', 'paid'],
    ['Mar. 27', 'Celebration of Spring', 'Sedona', 'Festival', 'mixed'],
    ['Mar. 28', 'Phoenix Suns vs. Toronto Raptors — 6:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Mar. 28', 'Arizona Dragon Boat Festival', 'Tempe Town Lake', 'Sports/Culture', 'free'],
    ['March', 'MLB Cactus League Spring Training', 'Scottsdale / Scottsdale Stadium', 'Baseball', 'paid'],
    ['March', 'Celebration of Fine Art', 'Scottsdale / Big White Tents', 'Fine Art', 'paid'],
    ['March', 'Scottsdale Art Week / related art events', 'Scottsdale', 'Art', 'paid'],
    ['March — TBD', 'Tucson Festival of Books', 'Tucson / University of Arizona', 'Books', 'free'],
    ['March — TBD', 'Cologuard Classic', 'Tucson', 'Golf', 'paid'],
    ['March — TBD', 'Arizona Renaissance Festival', 'Gold Canyon', 'Festival', 'paid'],
    ['March — TBD', 'AIA basketball/winter-sports championships', 'Arizona', 'High School Sports', 'paid'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
  ]),
  month('April 2027', [
    ['Apr. 2', 'Phoenix Suns vs. Denver Nuggets — 7:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Apr. 2–4', 'Art in Gold Canyon', 'Gold Canyon', 'Arts', 'free'],
    ['Apr. 2–4', 'Arizona Diamondbacks vs. Miami Marlins', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Apr. 2–4', 'ASU Baseball vs. Kansas State', 'Tempe', 'College Baseball', 'tbd'],
    ['Apr. 3–4', 'Arizona Renaissance Festival', 'Gold Canyon', 'Festival', 'paid'],
    ['Apr. 3', 'Fleetwood Mac: A Symphonic Tribute', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['Apr. 3', "I'm Not a Comedian… I'm Lenny Bruce", 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Apr. 3', 'Music Fest', 'Fountain Hills', 'Music', 'free'],
    ['Apr. 5–7', 'Arizona Diamondbacks vs. Los Angeles Dodgers', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Apr. 8', 'Viviana Performs Mozart', 'Phoenix / Musical Instrument Museum', 'Classical', 'paid'],
    ['Apr. 8', 'Desert Foothills Land Trust Boot & Bourbon Fundraiser', 'Cave Creek', 'Fundraiser', 'paid'],
    ['Apr. 8–11', 'Country Thunder Arizona', 'Florence', 'Country Music', 'paid'],
    ['Apr. 9', 'Phoenix Suns vs. Memphis Grizzlies — 7:00 PM', 'Phoenix', 'NBA', 'paid'],
    ['Apr. 9–11', 'The Taylor Swift Symphonic Experience', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['Apr. 9–11', 'ASU Softball vs. Houston', 'Tempe', 'College Softball', 'tbd'],
    ['Apr. 9–25', 'Waiting for Godot', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Apr. 9–11', 'Ballet Tucson', 'Tucson / Leo Rich Theatre', 'Dance', 'paid'],
    ['Apr. 10–11', 'Arizona Opera New Works Festival', 'Phoenix / Arizona Opera Center', 'Opera', 'paid'],
    ['Apr. 10–25', 'Gem of the Ocean', 'Phoenix / Phoenix Theatre', 'Theater', 'paid'],
    ['Apr. 10–25', 'Gem of the Ocean', 'Tucson / Arizona Theatre Company', 'Theater', 'paid'],
    ['Apr. 15', 'Concerts on the Avenue', 'Fountain Hills', 'Music', 'free'],
    ['Apr. 16–18', 'Arizona Diamondbacks vs. San Diego Padres', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Apr. 16–18', 'Bella, Britten & Sibelius', 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['Apr. 16–18', 'ASU Baseball vs. Arizona', 'Tempe', 'College Baseball', 'tbd'],
    ['Apr. 16–18', "ASU Men's Golf — Thunderbird Invitational", 'Arizona', 'College Golf', 'paid'],
    ['Apr. 19–21', 'Arizona Diamondbacks vs. Chicago Cubs', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Apr. 22–25', 'Region 7 Championship', 'Scottsdale', 'Arabian Horse', 'paid'],
    ['Apr. 23–30', 'Arizona Diamondbacks vs. Cleveland Guardians', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Apr. 23–25', 'Raiders of the Lost Ark in Concert', 'Phoenix / Symphony Hall', 'Music/Film', 'paid'],
    ['Apr. 23–25', 'South Pacific', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['Apr. 23–25', 'Art at Frontier Town', 'Cave Creek', 'Arts', 'free'],
    ['Apr. 23–25', 'ASU Softball vs. Iowa State', 'Tempe', 'College Softball', 'tbd'],
    ['Apr. 23–25', 'Red Rock Rally Pickleball Tournament', 'Sedona', 'Sports', 'paid'],
    ['Apr. 27–May 2', 'The Notebook', 'Tucson / Centennial Hall', 'Broadway', 'paid'],
    ['Apr. 30–May 2', 'Litton Leads Shostakovich & Brahms with Michelle Cann', 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['April', 'Arizona Bike Week', 'Scottsdale / WestWorld', 'Motorcycle/Festival', 'paid'],
    ['April — TBD', 'Tucson Folk Festival', 'Tucson', 'Music', 'free'],
    ['April — TBD', 'Fourth Avenue Spring Street Fair', 'Tucson', 'Arts/Shopping', 'free'],
    ['April — TBD', 'Agave Heritage Festival', 'Tucson', 'Food/Culture', 'paid'],
    ['April — TBD', 'Palo Verde Bloom Festival', 'Tucson', 'Nature/Culture', 'mixed'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
  ]),
  month('May 2027', [
    ['May 1–2', 'Arizona Diamondbacks vs. Cleveland Guardians', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['May 2', 'Cabaret Sessions: Duo Entre-Nous', 'Scottsdale / Taliesin West', 'Music', 'paid'],
    ['May 3–5', 'Arizona Diamondbacks vs. Baltimore Orioles', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['May 4', 'Gravity & Other Myths', 'Tucson / Centennial Hall', 'Dance/Circus', 'paid'],
    ['May 7–9', 'Arizona Diamondbacks vs. Texas Rangers', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['May 7–9', 'Mandy Gonzalez Sings Lin-Manuel Miranda', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['May 8', 'Music of the Stars: Cosmic Connections', 'Phoenix / Madison Center for the Arts', 'Music', 'paid'],
    ['May 14–16', "Mahler's 5th Symphony", 'Phoenix / Symphony Hall', 'Classical', 'paid'],
    ['May 17–19', 'Arizona Diamondbacks vs. Seattle Mariners', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['May 20–23', 'PBR World Finals: Championship', 'Glendale / Desert Diamond Arena', 'Bull Riding', 'paid'],
    ['May 20', 'Arizona Diamondbacks vs. Colorado Rockies', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['May 20', 'Mozart, Glass & Bartok', 'Phoenix / Musical Instrument Museum', 'Classical', 'paid'],
    ['May 21–23', 'Arizona Diamondbacks vs. Colorado Rockies', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['May 21–23', 'Symphonic Genesis & Phil Collins', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['May 21–23', 'SIX', 'Tucson / Centennial Hall', 'Broadway', 'paid'],
    ['May 22', 'Marshall Charloff & The Purple xPeRIeNCE', 'Phoenix / Herberger Theater Center', 'Music', 'paid'],
    ['May 28–29', 'Game On!', 'Phoenix / Symphony Hall', 'Music', 'paid'],
    ['May 31', 'Arizona Diamondbacks vs. Cincinnati Reds', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['May', 'Arizona Restaurant Week', 'Scottsdale restaurants', 'Food', 'paid'],
    ['May — TBD', 'Pueblos del Maiz', 'Tucson', 'Food/Culture', 'mixed'],
    ['May — TBD', 'Tucson International Mariachi Conference', 'Tucson', 'Music/Culture', 'paid'],
    ['May — TBD', 'Phippen Western Art Show & Sale', 'Prescott / Courthouse Plaza', 'Western Art', 'mixed'],
    ['May — TBD', 'Memorial Day weekend festivals', 'Statewide', 'Arts/Events', 'mixed'],
    ['May — TBD', 'CinePark / outdoor movie events', 'Chandler', 'Film', 'free'],
    ['May — TBD', 'Spring/Summer community events', 'Casa Grande', 'Community', 'mixed'],
    ['Thursdays', 'Scottsdale ArtWalk', 'Old Town Scottsdale', 'Art/Culture', 'free'],
  ]),
  month('June 2027', [
    ['June 1–2', 'Arizona Diamondbacks vs. Cincinnati Reds', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['June 4–6', 'Arizona Diamondbacks vs. San Francisco Giants', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['June 14–16', 'Arizona Diamondbacks vs. Atlanta Braves', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['June 18–20', 'Arizona Diamondbacks vs. Boston Red Sox', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['June 18–July 3', 'The Underpants', 'Phoenix / Herberger Theater Center', 'Theater', 'paid'],
    ['June 28–30', 'Arizona Diamondbacks vs. New York Mets', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['June 28–July 4', "World's Oldest Rodeo / Prescott Frontier Days", 'Prescott', 'Rodeo/Western', 'mixed'],
    ['June', 'June Days in Old Town', 'Scottsdale / Old Town', 'Community/Shopping', 'mixed'],
    ['June', 'Old Town Scottsdale Farmers Market', 'Scottsdale / Old Town', 'Farmers Market', 'free'],
    ['June', 'Scottsdale ArtWalk', 'Scottsdale / Old Town', 'Art/Culture', 'free'],
    ['June — TBD', 'Flagstaff Folk Festival', 'Flagstaff / Wheeler Park', 'Music', 'free'],
    ['June — TBD', 'Pride in the Pines', 'Flagstaff / Thorpe Park', 'Pride/Community', 'free'],
    ['June — TBD', 'Flagstaff Beer Festival', 'Flagstaff', 'Food/Drink', 'paid'],
    ['June — TBD', 'Flagstaff Piano Festival', 'Flagstaff', 'Music', 'paid'],
    ['June — TBD', 'Heritage Festival', 'Flagstaff / Museum of Northern Arizona', 'Culture', 'paid'],
    ['June — TBD', 'Prescott Bluegrass Festival', 'Prescott / Courthouse Plaza', 'Music', 'free'],
    ['June — TBD', 'Phippen Western Art Show', 'Prescott / Courthouse Plaza', 'Arts', 'mixed'],
    ['June — TBD', 'El Día de San Juan', 'Tucson / Mission Garden', 'Culture', 'free'],
    ['June — TBD', 'Juneteenth events', 'Statewide', 'Culture', 'mixed'],
    ['June — TBD', 'Summer concerts', 'Flagstaff', 'Music', 'free'],
    ['June — TBD', 'Summer art festivals', 'Prescott/Flagstaff', 'Arts', 'mixed'],
    ['June — TBD', 'Summer community activities', 'Fountain Hills', 'Community', 'free'],
    ['June — TBD', 'Phoenix Fan Fusion', 'Phoenix Convention Center', 'Pop Culture', 'paid'],
    ['June — TBD', 'Family Fun Fridays', 'Sedona', 'Family', 'free'],
  ]),
  month('July 2027', [
    ['July 1–4', 'Arizona Diamondbacks vs. San Francisco Giants', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['July 1–4', "World's Oldest Rodeo", 'Prescott', 'Rodeo', 'paid'],
    ['July 1–10', 'Scottsdale ArtWalk / Old Town activities', 'Scottsdale / Old Town', 'Art/Culture', 'free'],
    ['July 3–5', 'Art in the Park (tentative)', 'Flagstaff / Wheeler Park', 'Arts', 'free'],
    ['July 3', 'Prescott Rodeo Dance / Frontier Days events', 'Prescott', 'Western', 'mixed'],
    ['July 4', 'Scottsdale 4th of July Celebration', 'Scottsdale / WestWorld', 'Independence Day', 'mixed'],
    ['July 4', 'Prescott Frontier Days Rodeo Parade', 'Prescott', 'Parade', 'free'],
    ['July 4', 'Prescott Fourth of July / Freedom Festival', 'Prescott', 'Holiday', 'mixed'],
    ['July 4', 'Flagstaff Fourth of July', 'Flagstaff', 'Holiday', 'free'],
    ['July 4', 'Independence Day events', 'Phoenix metro', 'Holiday', 'mixed'],
    ['July 9–11', 'Medieval Mayhem Renaissance Faire', 'Show Low', 'Renaissance/Festival', 'paid'],
    ['July 10', 'Special Engagement Concert', 'Show Low', 'Music', 'paid'],
    ['July 15–18', 'White Mountain Square & Round Dance Festival', 'Show Low', 'Dance/Culture', 'paid'],
    ['July 16–18', 'Arizona Diamondbacks vs. Colorado Rockies', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['July 19–21', 'Arizona Diamondbacks vs. St. Louis Cardinals', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['July — TBD', 'Celtic Festival', 'Flagstaff', 'Culture/Music', 'paid'],
    ['July — TBD', 'Summer concert series', 'Flagstaff', 'Music', 'free'],
    ['July — TBD', 'Movies in the Park', 'Flagstaff / Heritage Square', 'Film', 'free'],
  ]),
  month('August 2027', [
    ['Aug. 2–4', 'Arizona Diamondbacks vs. Tampa Bay Rays', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Aug. 6–8', 'Arizona Diamondbacks vs. Houston Astros', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Aug. 12–15', 'Arizona Diamondbacks vs. Milwaukee Brewers', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Aug. 23–25', 'Arizona Diamondbacks vs. Washington Nationals', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
    ['Aug. 27–29', 'Arizona Diamondbacks vs. Philadelphia Phillies', 'Phoenix / Chase Field', 'Baseball', 'tbd'],
  ]),
];

export const AZ_ADMISSION_LABELS: Record<AzAdmission, string> = {
  free: 'Free',
  paid: 'Paid',
  mixed: 'Mixed',
  tbd: 'TBD',
};

export const AZ_ADMISSION_COLORS: Record<AzAdmission, string> = {
  free: '#22c55e',
  paid: '#eab308',
  mixed: '#3b82f6',
  tbd: '#9ca3af',
};
